### ISSUE TITLE
all code is in .zip files

### ISSUE THREAD

**Issue by fabianp** [unlearning-challenge/starting_kit#1]
so it's impossible to check from this website :-)

**Comment by fabianp** [comment]
yes, zip files are terrible for collaboration. How are we supposed to send pull requests, view diffs etc. with zip files?

Don't worry about users downloading the code. We'll provide a magic link like https://github.com/unlearning-challenge/starting_kit/archive/refs/heads/main.zip that automatically wraps the repo inside a single .zip file

**Comment by fabianp** [comment]
the repo should look like this one (https://github.com/unlearning-challenge/baselines) where one can see the individual files from the webpage. It should also not have top level single folder, one should see in the first page the README and

**Comment by LishengSun** [comment]
Thanks, I get it now. I will fix it.

**Comment by LishengSun** [comment]
Done :)

**Comment by fabianp** [comment]
excellent, thanks!
